---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-applications-root
  namespace: argocd
  labels:
    Product: DevOps
    ProductComponents: cicd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: appsets
    repoURL: https://github.com/SergeyDz/argocd-performance
    targetRevision: HEAD
    directory:
      recurse: true
  syncPolicy:
    automated: 
      selfHeal: true
      prune: true
    syncOptions: 
      - CreateNamespace=true