apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-performance-in-cluster-393
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: dev
    name: in-cluster
  project: project-7
  source:
    path: helm/argo-performance
    repoURL: https://github.com/SergeyDz/argocd-performance.git
    targetRevision: HEAD
    helm:
      valueFiles:
      - values.yaml
      parameters:
      - name: nameOverride
        value: argo-performance-in-cluster-393
  syncPolicy:
    automated: {}
    syncOptions: 
      - CreateNamespace=true