apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-16
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    Product: project-16
    ProductComponents: ArgoProject
    Environment: dev
    kind: project
    type: declarative
spec:
  description: Project for project-16 Product.

  sourceRepos:
  - '*'

  destinations:
  - namespace: '*'
    server: '*'
  
  # syncWindows:
  # - duration: 24h
  #   kind: deny
  #   schedule: 0 0 * * *
  #   namespaces:
  #   - '*'
  #   applications:
  #   - '*'
  #   clusters:
  #   - '*'

  clusterResourceWhitelist:
  - group: "*"
    kind: Namespace

  roles:
  - name: project-16-access
    description: project-16 access to the project-16 project.
    policies:
    - p, proj:project-16:project-16-access, applications, *, project-16/*, allow
    - p, proj:project-16:project-16-access, applications, create, project-16/*, deny
    - p, proj:project-16:project-16-access, applications, update, project-16/*, deny
    groups:
    - project-16
    - project-16-DevOps
    - project-16-PreProd
