apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-19
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    Product: project-19
    ProductComponents: ArgoProject
    Environment: dev
    kind: project
    type: declarative
spec:
  description: Project for project-19 Product.

  sourceRepos:
  - '*'

  destinations:
  - namespace: '*'
    server: '*'
  
  syncWindows:
  - duration: 24h
    kind: deny
    schedule: 0 0 * * *
    namespaces:
    - '*'
    applications:
    - '*'
    clusters:
    - '*'

  clusterResourceWhitelist:
  - group: "*"
    kind: Namespace

  roles:
  - name: project-19-access
    description: project-19 access to the project-19 project.
    policies:
    - p, proj:project-19:project-19-access, applications, *, project-19/*, allow
    - p, proj:project-19:project-19-access, applications, create, project-19/*, deny
    - p, proj:project-19:project-19-access, applications, update, project-19/*, deny
    groups:
    - project-19
    - project-19-DevOps
    - project-19-PreProd
