apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-1
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    Product: project-1
    ProductComponents: ArgoProject
    Environment: dev
    kind: project
    type: declarative
spec:
  description: Project for project-1 Product.

  sourceRepos:
  - '*'

  destinations:
  - namespace: '*'
    server: '*'
  
  syncWindows:
  - duration: 24h
    kind: deny
    schedule: 0 0 * * *
    namespaces:
    - '*'
    applications:
    - '*'
    clusters:
    - '*'

  clusterResourceWhitelist:
  - group: "*"
    kind: Namespace

  roles:
  - name: project-1-access
    description: project-1 access to the project-1 project.
    policies:
    - p, proj:project-1:project-1-access, applications, *, project-1/*, allow
    - p, proj:project-1:project-1-access, applications, create, project-1/*, deny
    - p, proj:project-1:project-1-access, applications, update, project-1/*, deny
    groups:
    - project-1
    - project-1-DevOps
    - project-1-PreProd
