apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-23
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    Product: project-23
    ProductComponents: ArgoProject
    Environment: dev
    kind: project
    type: declarative
spec:
  description: Project for project-23 Product.

  sourceRepos:
  - '*'

  destinations:
  - namespace: '*'
    server: '*'
  
  syncWindows:
  - duration: 24h
    kind: deny
    schedule: 0 0 * * *
    namespaces:
    - '*'
    applications:
    - '*'
    clusters:
    - '*'

  clusterResourceWhitelist:
  - group: "*"
    kind: Namespace

  roles:
  - name: project-23-access
    description: project-23 access to the project-23 project.
    policies:
    - p, proj:project-23:project-23-access, applications, *, project-23/*, allow
    - p, proj:project-23:project-23-access, applications, create, project-23/*, deny
    - p, proj:project-23:project-23-access, applications, update, project-23/*, deny
    groups:
    - project-23
    - project-23-DevOps
    - project-23-PreProd
