apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-29
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    Product: project-29
    ProductComponents: ArgoProject
    Environment: dev
    kind: project
    type: declarative
spec:
  description: Project for project-29 Product.

  sourceRepos:
  - '*'

  destinations:
  - namespace: '*'
    server: '*'
  
  # syncWindows:
  # - duration: 24h
  #   kind: deny
  #   schedule: 0 0 * * *
  #   namespaces:
  #   - '*'
  #   applications:
  #   - '*'
  #   clusters:
  #   - '*'

  clusterResourceWhitelist:
  - group: "*"
    kind: Namespace

  roles:
  - name: project-29-access
    description: project-29 access to the project-29 project.
    policies:
    - p, proj:project-29:project-29-access, applications, *, project-29/*, allow
    - p, proj:project-29:project-29-access, applications, create, project-29/*, deny
    - p, proj:project-29:project-29-access, applications, update, project-29/*, deny
    groups:
    - project-29
    - project-29-DevOps
    - project-29-PreProd
