apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-28
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    Product: project-28
    ProductComponents: ArgoProject
    Environment: dev
    kind: project
    type: declarative
spec:
  description: Project for project-28 Product.

  sourceRepos:
  - '*'

  destinations:
  - namespace: '*'
    server: '*'
  
  # syncWindows:
  # - duration: 24h
  #   kind: deny
  #   schedule: 0 0 * * *
  #   namespaces:
  #   - '*'
  #   applications:
  #   - '*'
  #   clusters:
  #   - '*'

  clusterResourceWhitelist:
  - group: "*"
    kind: Namespace

  roles:
  - name: project-28-access
    description: project-28 access to the project-28 project.
    policies:
    - p, proj:project-28:project-28-access, applications, *, project-28/*, allow
    - p, proj:project-28:project-28-access, applications, create, project-28/*, deny
    - p, proj:project-28:project-28-access, applications, update, project-28/*, deny
    groups:
    - project-28
    - project-28-DevOps
    - project-28-PreProd
