apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-12
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    Product: project-12
    ProductComponents: ArgoProject
    Environment: dev
    kind: project
    type: declarative
spec:
  description: Project for project-12 Product.

  sourceRepos:
  - '*'

  destinations:
  - namespace: '*'
    server: '*'
  
  syncWindows:
  - duration: 24h
    kind: deny
    schedule: 0 0 * * *
    namespaces:
    - '*'
    applications:
    - '*'
    clusters:
    - '*'

  clusterResourceWhitelist:
  - group: "*"
    kind: Namespace

  roles:
  - name: project-12-access
    description: project-12 access to the project-12 project.
    policies:
    - p, proj:project-12:project-12-access, applications, *, project-12/*, allow
    - p, proj:project-12:project-12-access, applications, create, project-12/*, deny
    - p, proj:project-12:project-12-access, applications, update, project-12/*, deny
    groups:
    - project-12
    - project-12-DevOps
    - project-12-PreProd
