apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-20
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    Product: project-20
    ProductComponents: ArgoProject
    Environment: dev
    kind: project
    type: declarative
spec:
  description: Project for project-20 Product.

  sourceRepos:
  - '*'

  destinations:
  - namespace: '*'
    server: '*'
  
  syncWindows:
  - duration: 24h
    kind: deny
    schedule: 0 0 * * *
    namespaces:
    - '*'
    applications:
    - '*'
    clusters:
    - '*'

  clusterResourceWhitelist:
  - group: "*"
    kind: Namespace

  roles:
  - name: project-20-access
    description: project-20 access to the project-20 project.
    policies:
    - p, proj:project-20:project-20-access, applications, *, project-20/*, allow
    - p, proj:project-20:project-20-access, applications, create, project-20/*, deny
    - p, proj:project-20:project-20-access, applications, update, project-20/*, deny
    groups:
    - project-20
    - project-20-DevOps
    - project-20-PreProd
