apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-17
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    Product: project-17
    ProductComponents: ArgoProject
    Environment: dev
    kind: project
    type: declarative
spec:
  description: Project for project-17 Product.

  sourceRepos:
  - '*'

  destinations:
  - namespace: '*'
    server: '*'
  
  # syncWindows:
  # - duration: 24h
  #   kind: deny
  #   schedule: 0 0 * * *
  #   namespaces:
  #   - '*'
  #   applications:
  #   - '*'
  #   clusters:
  #   - '*'

  clusterResourceWhitelist:
  - group: "*"
    kind: Namespace

  roles:
  - name: project-17-access
    description: project-17 access to the project-17 project.
    policies:
    - p, proj:project-17:project-17-access, applications, *, project-17/*, allow
    - p, proj:project-17:project-17-access, applications, create, project-17/*, deny
    - p, proj:project-17:project-17-access, applications, update, project-17/*, deny
    groups:
    - project-17
    - project-17-DevOps
    - project-17-PreProd
