apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-22
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    Product: project-22
    ProductComponents: ArgoProject
    Environment: dev
    kind: project
    type: declarative
spec:
  description: Project for project-22 Product.

  sourceRepos:
  - '*'

  destinations:
  - namespace: '*'
    server: '*'
  
  syncWindows:
  - duration: 24h
    kind: deny
    schedule: 0 0 * * *
    namespaces:
    - '*'
    applications:
    - '*'
    clusters:
    - '*'

  clusterResourceWhitelist:
  - group: "*"
    kind: Namespace

  roles:
  - name: project-22-access
    description: project-22 access to the project-22 project.
    policies:
    - p, proj:project-22:project-22-access, applications, *, project-22/*, allow
    - p, proj:project-22:project-22-access, applications, create, project-22/*, deny
    - p, proj:project-22:project-22-access, applications, update, project-22/*, deny
    groups:
    - project-22
    - project-22-DevOps
    - project-22-PreProd
