apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-13
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    Product: project-13
    ProductComponents: ArgoProject
    Environment: dev
    kind: project
    type: declarative
spec:
  description: Project for project-13 Product.

  sourceRepos:
  - '*'

  destinations:
  - namespace: '*'
    server: '*'
  
  # syncWindows:
  # - duration: 24h
  #   kind: deny
  #   schedule: 0 0 * * *
  #   namespaces:
  #   - '*'
  #   applications:
  #   - '*'
  #   clusters:
  #   - '*'

  clusterResourceWhitelist:
  - group: "*"
    kind: Namespace

  roles:
  - name: project-13-access
    description: project-13 access to the project-13 project.
    policies:
    - p, proj:project-13:project-13-access, applications, *, project-13/*, allow
    - p, proj:project-13:project-13-access, applications, create, project-13/*, deny
    - p, proj:project-13:project-13-access, applications, update, project-13/*, deny
    groups:
    - project-13
    - project-13-DevOps
    - project-13-PreProd
