apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-10
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    Product: project-10
    ProductComponents: ArgoProject
    Environment: dev
    kind: project
    type: declarative
spec:
  description: Project for project-10 Product.

  sourceRepos:
  - '*'

  destinations:
  - namespace: '*'
    server: '*'
  
  # syncWindows:
  # - duration: 24h
  #   kind: deny
  #   schedule: 0 0 * * *
  #   namespaces:
  #   - '*'
  #   applications:
  #   - '*'
  #   clusters:
  #   - '*'

  clusterResourceWhitelist:
  - group: "*"
    kind: Namespace

  roles:
  - name: project-10-access
    description: project-10 access to the project-10 project.
    policies:
    - p, proj:project-10:project-10-access, applications, *, project-10/*, allow
    - p, proj:project-10:project-10-access, applications, create, project-10/*, deny
    - p, proj:project-10:project-10-access, applications, update, project-10/*, deny
    groups:
    - project-10
    - project-10-DevOps
    - project-10-PreProd
