apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-27
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    Product: project-27
    ProductComponents: ArgoProject
    Environment: dev
    kind: project
    type: declarative
spec:
  description: Project for project-27 Product.

  sourceRepos:
  - '*'

  destinations:
  - namespace: '*'
    server: '*'
  
  # syncWindows:
  # - duration: 24h
  #   kind: deny
  #   schedule: 0 0 * * *
  #   namespaces:
  #   - '*'
  #   applications:
  #   - '*'
  #   clusters:
  #   - '*'

  clusterResourceWhitelist:
  - group: "*"
    kind: Namespace

  roles:
  - name: project-27-access
    description: project-27 access to the project-27 project.
    policies:
    - p, proj:project-27:project-27-access, applications, *, project-27/*, allow
    - p, proj:project-27:project-27-access, applications, create, project-27/*, deny
    - p, proj:project-27:project-27-access, applications, update, project-27/*, deny
    groups:
    - project-27
    - project-27-DevOps
    - project-27-PreProd
