apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-11
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    Product: project-11
    ProductComponents: ArgoProject
    Environment: dev
    kind: project
    type: declarative
spec:
  description: Project for project-11 Product.

  sourceRepos:
  - '*'

  destinations:
  - namespace: '*'
    server: '*'
  
  syncWindows:
  - duration: 24h
    kind: deny
    schedule: 0 0 * * *
    namespaces:
    - '*'
    applications:
    - '*'
    clusters:
    - '*'

  clusterResourceWhitelist:
  - group: "*"
    kind: Namespace

  roles:
  - name: project-11-access
    description: project-11 access to the project-11 project.
    policies:
    - p, proj:project-11:project-11-access, applications, *, project-11/*, allow
    - p, proj:project-11:project-11-access, applications, create, project-11/*, deny
    - p, proj:project-11:project-11-access, applications, update, project-11/*, deny
    groups:
    - project-11
    - project-11-DevOps
    - project-11-PreProd
