apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-24
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    Product: project-24
    ProductComponents: ArgoProject
    Environment: dev
    kind: project
    type: declarative
spec:
  description: Project for project-24 Product.

  sourceRepos:
  - '*'

  destinations:
  - namespace: '*'
    server: '*'
  
  syncWindows:
  - duration: 24h
    kind: deny
    schedule: 0 0 * * *
    namespaces:
    - '*'
    applications:
    - '*'
    clusters:
    - '*'

  clusterResourceWhitelist:
  - group: "*"
    kind: Namespace

  roles:
  - name: project-24-access
    description: project-24 access to the project-24 project.
    policies:
    - p, proj:project-24:project-24-access, applications, *, project-24/*, allow
    - p, proj:project-24:project-24-access, applications, create, project-24/*, deny
    - p, proj:project-24:project-24-access, applications, update, project-24/*, deny
    groups:
    - project-24
    - project-24-DevOps
    - project-24-PreProd
